version: '3'
services:
  mlflow:
    image: ghcr.io/mlflow/mlflow:latest
    ports:
      - "5555:5000"
    command: >
      mlflow server
      --host 0.0.0.0
      --backend-store-uri sqlite:///mlflow/mlflow.db
      --default-artifact-root /mlflow-artifacts
    volumes:
      - ./mlflow:/mlflow
      - ./mlruns:/mlflow-artifacts
    container_name: mlflow-tracking-server
